### ISSUE TITLE
GitHub runs table not updated after second attempt

### ISSUE THREAD

**Issue by elecnix** [nineinchnick/trino-rest#235]
A workflow run that fails on first attempt will get selected by [Sync::syncRuns](https://github.com/nineinchnick/trino-rest/blob/84a777a7b2626a1480c57d72513c2b7795107373/trino-rest-github/src/main/java/pl/net/was/rest/github/Sync.java#L959) because it is completed.

If the second attempt completes after the sync, the destination table already have a row with this ID, so it is not sync'ed.

As a result, the runs table will not reflect the successful second attempt.

**Comment by nineinchnick** [comment]
Sounds like we should get the max run ID only for run that cannot be retried, so completed successfully.

**Comment by nineinchnick** [comment]
Done in 7656ba0eb2ea535f1cde98d76d81b7c3125999c8
