### ISSUE TITLE
Make min number of splits configurable

### ISSUE THREAD

**Issue by nineinchnick** [nineinchnick/trino-rest#62]
Right now, for tables for which the total number of rows can't be determined, there will always be 4 splits to fetch data in parallel. Make this number configurable.

**Comment by AyushWalekar** [comment]
Hi @nineinchnick , I am new to open source. Please let me know if I can get started with this one.
Thanks!

**Comment by AyushWalekar** [comment]
#66 Added PR for review.

**Comment by nineinchnick** [comment]
This is great, thanks a lot! I'm excited that anyone wants to contribute here :-)
